-- AlterTable
ALTER TABLE "AppUser" ADD COLUMN     "aiRequests" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "embedsCreated" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastActive" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "webhooksSent" INTEGER NOT NULL DEFAULT 0;
